### ISSUE TITLE
Slider's default direction is reversed. How set mouse wheel direction?

### ISSUE THREAD

**Issue by magreenblatt** [chromiumembedded/java-cef#220]
**[Original report](https://bitbucket.org/chromiumembedded/java-cef/issues/220) by Wang Zl (Bitbucket: [luciferwzl](https://bitbucket.org/luciferwzl), GitHub: [luciferwzl](https://github.com/luciferwzl)).**

----------------------------------------

Hi,

I am run a simple example. Slider's default direction was reversed when I control scroll by mouse wheel.

How set mouse wheel direction?

**Comment by 1053950438** [comment]
When I changed it to false, the program froze directly and couldn't be clicked
