### ISSUE TITLE
Load html directly

### ISSUE THREAD

**Issue by LansV** [chromiumembedded/java-cef#453]
Hello,
I want to load the directly generated html text directly in the browser instead of using loadUrl()

**Comment by JScheiterbauer** [comment]
Hi!
You can use data urls for this: See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs 
Only thing is they have length limitation.
If this is getting a problem, you can also write it to the file system and load it via file:// url

**Comment by LansV** [comment]
Thank you for your answer
It would be great if there is native method support

**Comment by JScheiterbauer** [comment]
This was available once but then removed (don't know why...)

**Comment by magreenblatt** [comment]
This is not supported by Chromium. See https://github.com/chromiumembedded/cef/issues/2586
