### ISSUE TITLE
Unwanted behavior -  Ctrl+Wheel zooms the whole window now

### ISSUE THREAD

**Issue by tomaszkunicki** [chromiumembedded/java-cef#454]
**Describe the bug**
In previous versions the window was not handling Ctrl+wheel since version 118 it's new behavior which breaks the code which was handling Ctrl+wheel events by itself.

The event can be blocked on Javascript level though.

**To Reproduce**
1. Open cefclient
2.Press Ctrl and use mouse wheel
3. The whole screen changes the zoom

**Expected behavior**
Do not handle zoom by browser

**Versions (please complete the following information):**
 - OS:  Windows11
 - CEF Version: [e.g. 118.6.7.]

**Comment by magreenblatt** [comment]
This behavior can be disabled using JavaScript, see https://stackoverflow.com/a/57582286
